service: shopify-mvp

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.12
  region: us-east-1

functions:
  app:
    handler: handler.app
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
